# ============================================
# CUSTOM SCALARS
# ============================================

"""
DateTime scalar type
Formato: ISO 8601 (YYYY-MM-DDTHH:mm:ssZ)
Exemplo: 2026-04-16T14:30:00Z
"""
scalar DateTime

scalar Date

"""
Enuns
"""

enum Roles {
    USER 
    ADMIN 
    SUPER_ADMIN 
}

enum ExpirationApiKey {
    ONE_HOUR 
    ONE_DAY 
    TWO_DAYS 
    SEVEN_DAYS 
    THIRTY_DAYS
    NINETY_DAYS
    ONE_YEAR
}

"""
Types
"""
type ApiErrorType {
    errorName: String!
    typeError: String!
    statusCode: Int
}

type UserPublicType {
    name: String
    email: String!
    createdAt: DateTime
    updatedAt: DateTime
}

type UserPrivateType {
    userId: String!
    name: String
    email: String!
    password: String
    role: Roles
    isDeleted: Boolean
    createdAt: DateTime
    updatedAt: DateTime
}

type SessionType {
    sessionId: String!
    createdAt: DateTime!
    expiresAt: DateTime!
}

type TwoFactorAuthType {
    token: String!
    number: Int!
    expiresAt: DateTime
}

type ApiKeyType {
    token: String
    expiresAt: DateTime
}

type UserListType {
    root: [UserPrivateType]
}

type PasswordResetType {
    token: String!
    number: String
}


"""
Inputs
"""
input UserInput {
    name: String
    email: String
    password: String
}

input UserPrivateInput {
    name: String
    email: String
    password: String
    role: Roles
}

input UserUpdatePublicInput {
    name: String
}

input UserUpdatePrivateInput {
    userId: String!
    name: String
    email: String
    role: Roles 
    password: String
}

input UserLoginInput {
    email: String!
    password: String!
}

input PaginationInput {
    page: Int
    limit: Int
    all_: Boolean
}

input FilterByInput {
    name: String
    createdAt: Date
    isDeleted: Boolean
    role: Roles
}

input Verify2FAInput {
    number: Int!
    token: String!
}

input ForgotPasswordInput {
    email: String!
}

input UserResetPasswordInput {
    password: String!
    token: String!
}

input ApiKeyInput {
    expiration: ExpirationApiKey
}

input ListInput {
    pagination: PaginationInput!
    filterBy: FilterByInput
}


# Mutations 
type AdminApiKeyMutation {
    create(schema: ApiKeyInput!): ApiKeyType!
    delete(key: String!): ApiKeyType
}

type AccountMutation {
    updateProfile(schema: UserUpdatePublicInput): UserPublicType!
    deleteAccount: UserPublicType
}

type AuthMutation {
    register(schema: UserInput): UserPublicType!
    login(schema: UserLoginInput!): TwoFactorAuthType!
    verifyTwoFactor (schema: Verify2FAInput): SessionType!
    forgotPassword(schema: ForgotPasswordInput): PasswordResetType!
    resetPassword(schema: UserResetPasswordInput): UserPublicType!
}

type AdminUserMutation {
    create(schema: UserPrivateInput!): UserPrivateType!
    update(schema: UserUpdatePrivateInput!): UserPrivateType!
    delete(userId: String!): UserPrivateType
}

type AdminMutation {
    users: AdminUserMutation
    apiKey: AdminApiKeyMutation
}

# Base Mutation
type Mutation {
    admin: AdminMutation 
    user: AccountMutation
    auth: AuthMutation
}

# Queries
type AccountQuery {
    me: UserPublicType!
}

type AdminUserQuery {
    list(input: ListInput): UserListType!
    getById(userId: String!): UserPrivateType!
}

type AdminQuery {
    users: AdminUserQuery
}

# Base Query
type Query {
    account: AccountQuery
    admin: AdminQuery
}


